[33m16:14:11 (54382) WARN ProjectReader[39m Glob pattern "**/node_modules/**" did not result in any files.
[33m16:14:11 (54382) WARN ProjectReader[39m Glob pattern "**/vendor/**" did not result in any files.
[32m16:14:11 (54382) INFO ProjectReader[39m Found 41 of 649 file(s) to be mutated.
[32m16:14:11 (54382) INFO Instrumenter[39m Instrumented 41 source file(s) with 2936 mutant(s)
[32m16:14:11 (54382) INFO ConcurrencyTokenProvider[39m Creating 7 test runner process(es).
[32m16:14:12 (54382) INFO DryRunExecutor[39m Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
[32m16:14:27 (54382) INFO DryRunExecutor[39m Initial test run succeeded. Ran 971 tests in 15 seconds (net 7524 ms, overhead 7705 ms).
[33m16:20:23 (54382) WARN ChildProcessProxy[39m Child process [pid 70367] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 70367] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 70367,
  exitCode: 1,
  signal: null
}
[33m16:20:24 (54382) WARN ChildProcessProxy[39m Child process [pid 70526] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 70526] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 70526,
  exitCode: 1,
  signal: null
}
[33m16:20:29 (54382) WARN ChildProcessProxy[39m Child process [pid 71156] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 71156] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 71156,
  exitCode: 1,
  signal: null
}
[33m16:20:30 (54382) WARN ChildProcessProxy[39m Child process [pid 69383] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 69383] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 69383,
  exitCode: 1,
  signal: null
}
[33m16:20:31 (54382) WARN ChildProcessProxy[39m Child process [pid 71115] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 71115] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 71115,
  exitCode: 1,
  signal: null
}
[33m16:20:36 (54382) WARN ChildProcessProxy[39m Child process [pid 72061] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 72061] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 72061,
  exitCode: 1,
  signal: null
}
[33m16:23:08 (54382) WARN ChildProcessProxy[39m Child process [pid 78729] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 78729] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 78729,
  exitCode: 1,
  signal: null
}
[33m16:23:10 (54382) WARN ChildProcessProxy[39m Child process [pid 79615] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 79615] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-1eUCAr/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 79615,
  exitCode: 1,
  signal: null
}
