[33m19:18:03 (78179) WARN ProjectReader[39m Glob pattern "**/node_modules/**" did not result in any files.
[33m19:18:03 (78179) WARN ProjectReader[39m Glob pattern "**/vendor/**" did not result in any files.
[32m19:18:03 (78179) INFO ProjectReader[39m Found 40 of 437 file(s) to be mutated.
[32m19:18:04 (78179) INFO Instrumenter[39m Instrumented 40 source file(s) with 2923 mutant(s)
[32m19:18:04 (78179) INFO ConcurrencyTokenProvider[39m Creating 7 test runner process(es).
[32m19:18:04 (78179) INFO DryRunExecutor[39m Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
[32m19:18:14 (78179) INFO DryRunExecutor[39m Initial test run succeeded. Ran 619 tests in 9 seconds (net 6453 ms, overhead 3471 ms).
[33m19:18:14 (78179) WARN MutantTestPlanner[39m Detected 213 static mutants (7% of total) that are estimated to take 50% of the time running the tests!
  You might want to enable "ignoreStatic" to ignore these static mutants for your next run. 
  For more information about static mutants visit: https://stryker-mutator.io/docs/mutation-testing-elements/static-mutants
  (disable "warnings.slow" to ignore this warning)
[33m19:20:21 (78179) WARN ChildProcessProxy[39m Child process [pid 94488] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 94488] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 94488,
  exitCode: 1,
  signal: null
}
[33m19:20:22 (78179) WARN ChildProcessProxy[39m Child process [pid 78194] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:75
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:86:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 78194] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:75
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:86:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 78194,
  exitCode: 1,
  signal: null
}
[33m19:20:22 (78179) WARN ChildProcessProxy[39m Child process [pid 94816] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 94816] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 94816,
  exitCode: 1,
  signal: null
}
[33m19:20:24 (78179) WARN ChildProcessProxy[39m Child process [pid 96092] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 96092] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 96092,
  exitCode: 1,
  signal: null
}
[33m19:20:24 (78179) WARN ChildProcessProxy[39m Child process [pid 96091] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:75
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:86:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 96091] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:75
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/test/browser/toys.handleRequestResponse.test.js:86:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 96091,
  exitCode: 1,
  signal: null
}
[33m19:20:25 (78179) WARN ChildProcessProxy[39m Child process [pid 96049] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 96049] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:842:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  innerError: undefined,
  pid: 96049,
  exitCode: 1,
  signal: null
}
[33m19:21:15 (78179) WARN ChildProcessProxy[39m Child process [pid 78215] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 78215] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 78215,
  exitCode: 1,
  signal: null
}
[33m19:21:16 (78179) WARN ChildProcessProxy[39m Child process [pid 1356] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 1356] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 5 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:529:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-qgidn3/src/browser/toys.js:838:9
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 1356,
  exitCode: 1,
  signal: null
}
