[32m19:51:14 (85434) INFO ProjectReader[39m Found 43 of 390 file(s) to be mutated.
[32m19:51:14 (85434) INFO Instrumenter[39m Instrumented 43 source file(s) with 3139 mutant(s)
[32m19:51:14 (85434) INFO ConcurrencyTokenProvider[39m Creating 7 test runner process(es).
[32m19:51:15 (85434) INFO DryRunExecutor[39m Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
[91m19:51:28 (85434) ERROR DryRunExecutor[39m One or more tests resulted in an error:
	
Missing coverage results for:
  * test/browser/toys.keyValueInput.test.js
  * test/browser/toys.createKeyValueRow.test.js
  * test/browser/toys.syncHiddenField.test.js
  (and 14 more)

You probably configured a test environment in jest that is not reporting code coverage to Stryker. 
See also https://jestjs.io/docs/en/configuration.html#testenvironment-string

Are you using node, jsdom or jsdom-sixteen as a test environment? Please change that:
  * node -> @stryker-mutator/jest-runner/jest-env/node
  * jsdom -> @stryker-mutator/jest-runner/jest-env/jsdom
  * jest-environment-jsdom-sixteen -> @stryker-mutator/jest-runner/jest-env/jsdom-sixteen

If you're using your own custom test environment, please enrich the environment with this mixin: 

const { mixinJestEnvironment} = require('@stryker-mutator/jest-runner');
module.exports = mixinJestEnvironment(MyCustomTestEnvironment);

For more info, see https://stryker-mutator.io/docs/stryker-js/jest-runner#coverage-analysis
[91m19:51:28 (85434) ERROR Stryker[39m Unexpected error occurred while running Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/process/3-dry-run-executor.js:76:15)
    at DryRunExecutor.executeDryRun (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/process/3-dry-run-executor.js:96:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async WorkItem.execute (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/concurrent/pool.js:32:28)
    at async file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/concurrent/pool.js:69:13
[32m19:51:28 (85434) INFO Stryker[39m This might be a known problem with a solution documented in our troubleshooting guide.
[32m19:51:28 (85434) INFO Stryker[39m You can find it at https://stryker-mutator.io/docs/stryker-js/troubleshooting/
[32m19:51:28 (85434) INFO Stryker[39m Still having trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
