[33m21:59:14 (45502) WARN ProjectReader[39m Glob pattern "**/node_modules/**" did not result in any files.
[33m21:59:14 (45502) WARN ProjectReader[39m Glob pattern "**/vendor/**" did not result in any files.
[32m21:59:14 (45502) INFO ProjectReader[39m Found 47 of 675 file(s) to be mutated.
[32m21:59:15 (45502) INFO Instrumenter[39m Instrumented 47 source file(s) with 3124 mutant(s)
[32m21:59:15 (45502) INFO ConcurrencyTokenProvider[39m Creating 7 test runner process(es).
[32m21:59:15 (45502) INFO DryRunExecutor[39m Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
[32m21:59:28 (45502) INFO DryRunExecutor[39m Initial test run succeeded. Ran 980 tests in 12 seconds (net 4576 ms, overhead 8246 ms).
[33m22:05:08 (45502) WARN ChildProcessProxy[39m Child process [pid 58075] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 58075] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 58075,
  exitCode: 1,
  signal: null
}
[33m22:05:09 (45502) WARN ChildProcessProxy[39m Child process [pid 58046] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 58046] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 58046,
  exitCode: 1,
  signal: null
}
[33m22:05:09 (45502) WARN ChildProcessProxy[39m Child process [pid 58107] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 58107] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 58107,
  exitCode: 1,
  signal: null
}
[33m22:05:11 (45502) WARN ChildProcessProxy[39m Child process [pid 61541] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 61541] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  innerError: undefined,
  pid: 61541,
  exitCode: 1,
  signal: null
}
[33m22:05:12 (45502) WARN ChildProcessProxy[39m Child process [pid 61582] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 61582] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 61582,
  exitCode: 1,
  signal: null
}
[33m22:05:13 (45502) WARN ChildProcessProxy[39m Child process [pid 61410] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 61410] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:720:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 61410,
  exitCode: 1,
  signal: null
}
[33m22:07:25 (45502) WARN ChildProcessProxy[39m Child process [pid 65503] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 65503] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 65503,
  exitCode: 1,
  signal: null
}
[33m22:07:27 (45502) WARN ChildProcessProxy[39m Child process [pid 66888] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 66888] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 15 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:406:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-tYQfiv/src/browser/toys.js:716:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  innerError: undefined,
  pid: 66888,
  exitCode: 1,
  signal: null
}
