[33m07:50:43 (86460) WARN ProjectReader[39m Glob pattern "**/node_modules/**" did not result in any files.
[33m07:50:43 (86460) WARN ProjectReader[39m Glob pattern "**/vendor/**" did not result in any files.
[32m07:50:43 (86460) INFO ProjectReader[39m Found 42 of 690 file(s) to be mutated.
[32m07:50:43 (86460) INFO Instrumenter[39m Instrumented 42 source file(s) with 2989 mutant(s)
[32m07:50:43 (86460) INFO ConcurrencyTokenProvider[39m Creating 7 test runner process(es).
[32m07:50:44 (86460) INFO DryRunExecutor[39m Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
[32m07:51:00 (86460) INFO DryRunExecutor[39m Initial test run succeeded. Ran 1019 tests in 15 seconds (net 7116 ms, overhead 8856 ms).
[33m07:57:27 (86460) WARN ChildProcessProxy[39m Child process [pid 2950] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 2950] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 2950,
  exitCode: 1,
  signal: null
}
[33m07:57:29 (86460) WARN ChildProcessProxy[39m Child process [pid 2975] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 2975] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 2975,
  exitCode: 1,
  signal: null
}
[33m07:57:31 (86460) WARN ChildProcessProxy[39m Child process [pid 205] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 205] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 205,
  exitCode: 1,
  signal: null
}
[33m07:57:32 (86460) WARN ChildProcessProxy[39m Child process [pid 3392] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 3392] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844
	        dom.addWarning(parent);
	            ^
	
	TypeError: dom.addWarning is not a function
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:844:13
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 3392,
  exitCode: 1,
  signal: null
}
[33m07:57:33 (86460) WARN ChildProcessProxy[39m Child process [pid 3476] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 3476] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:86
	    const error = new Error('Network error');
	                  ^
	
	Error: Network error
	    at Object.<anonymous> (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/test/browser/toys.handleRequestResponse.test.js:98:19)
	    at Promise.then.completed (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:298:28)
	    at new Promise (<anonymous>)
	    at callAsyncCircusFn (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/utils.js:231:10)
	    at _callCircusTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:316:40)
	    at processTicksAndRejections (node:internal/process/task_queues:105:5)
	    at _runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:252:3)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:126:9)
	    at _runTestsForDescribeBlock (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:121:9)
	    at run (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/run.js:71:3)
	    at runAndTransformResultsToJestFormat (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
	    at jestAdapter (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
	    at runTestInternal (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:367:16)
	    at runTest (/Users/matthew.heard/Code/Matt/dadeto/node_modules/jest-runner/build/runTest.js:444:34)
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 3476,
  exitCode: 1,
  signal: null
}
[33m07:57:34 (86460) WARN ChildProcessProxy[39m Child process [pid 3559] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 3559] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 3559,
  exitCode: 1,
  signal: null
}
[33m07:59:54 (86460) WARN ChildProcessProxy[39m Child process [pid 7324] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 7324] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 7324,
  exitCode: 1,
  signal: null
}
[33m07:59:56 (86460) WARN ChildProcessProxy[39m Child process [pid 9000] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	 ChildProcessCrashedError: Child process [pid 9000] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	watchman warning:  Recrawled this watch 13 times, most recently because:
	MustScanSubDirs UserDroppedTo resolve, please review the information on
	https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
	To clear this warning, run:
	`watchman watch-del '/Users/matthew.heard/Code/Matt/dadeto' ; watchman watch-project '/Users/matthew.heard/Code/Matt/dadeto'`
	
	/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530
	    const child = presenter(output.content, dom);
	                  ^
	
	TypeError: presenter is not a function
	    at setTextContent (/Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:530:19)
	    at /Users/matthew.heard/Code/Matt/dadeto/.stryker-tmp/sandbox-ZSuplM/src/browser/toys.js:840:9
	
	Node.js v23.5.0
	
    at ChildProcess.handleUnexpectedExit (file:///Users/matthew.heard/Code/Matt/dadeto/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:178:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:351:12) {
  innerError: undefined,
  pid: 9000,
  exitCode: 1,
  signal: null
}
